before_script:
  - PATH=/usr/local/bin:$PATH

deploy:develop:
  stage: deploy
  script:
    - PATH=/home/gitlab-runner/.nvm/versions/node/v8.11.4/bin/:$PATH
    - npm install
    - echo $DEV_ENV > .env.production
    - node converEnv.js .env.production
    - npm run build
    - rm -rf $DEV_DEPLOY_DIRECTORY
    - cp -r dist $DEV_DEPLOY_DIRECTORY
  cache:
    paths:
      - node_modules
  only:
    - develop
  tags:
    - TAG
